spring:
  ai:
    zhipuai:
      api-key: ${ZHIPUAI_API_KEY}

    vectorstore:
      elasticsearch:
        initialize-schema: true
        index-name: rag-document-index
        dimensions: 1536
        similarity: cosine

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /docs
    operationsSorter: method
    tagsSorter: alpha
    displayRequestDuration: true
